### ISSUE TITLE
Where do we want to define the service test configuration

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/ansible-provisioning#28]
Ideally, we want to let the user define a service test as a task, at the same place where they deploy the application with reasonable default settings. Users get the monitored service and at least some monitoring coverage, e.g. for a web site something like this:

```yaml
onms_service:
  HTTP.MyApp:
    path: /
    return-code: 200
```
Each role which wants to add a service test configuration, appends to the dictionary and the horizon-provisioning role at the end, applies the services on the nodes IP interfaces.
